################################################################################
# composer settings file
################################################################################

variables:
  title-prefix:				"Tresobis"

########################################
  site-config:

    homepage:				http://www.tresobis.org
    brand:				null
    copyright: |
      <!-- composer >> icon copyright >> -->
      Copyright (c) 2023, Gary B. Genett

    search_name: |
      <!-- composer >> icon search >> -->
    search_site:			https://duckduckgo.com
    search_call:			q
    search_form: |
      <!-- composer >> form sites tresobis.org >> -->
      <!-- composer >> form ia web >> -->
      <!-- composer >> form kae d >> -->
      <!-- composer >> form ko 1 >> -->
      <!-- composer >> form kp -1 >> -->
      <!-- composer >> form kv 1 >> -->
      <!-- composer >> form kz -1 >> -->

    header:				<composer_root>/_header.md.cms
    footer:				<composer_root>/_footer.md.cms

#>  css_shade:				custom
    css_shade:				null
    copy_protect:			1

    cols_break:				md
    cols_order:				[ 2, 1, 0 ]
    cols_reorder:			[ 0, 1, 0 ]
    cols_size:				[ 4, 8, 0 ]
    cols_resize:			[ 0, 12, 0 ]

    tagslist:
      type:
        title:				"Type"
        display:			"*Type: <|>, <|>*"

########################################
  site-library:

    folder:				library
    auto_update:			null #>>> 1

    digest_count:			20

    sitemap_spacer:			null

    lists_expanded:			null
    lists_spacer:			null

########################################
  site-nav-top:

    MENU:
      - Latest:				<composer_root>/index.html
#>  CONTENTS:
#>    - Contents:
#>      - contents 0
#>  SPACE:
#>    - spacer
    LIBRARY:
      - Authors:
        - library author
      - Types:
        - library type
      - Tags:
        - library tags
      - History:
        - library date
    SPACE:
      - spacer
    CONTENTS:
      - Contents:
        - contents 0

########################################
  site-nav-bottom:

    PATH:
      - Sitemap:			<composer_root>/library/sitemap.html
    INFO:
      - tagslist author
      - tagslist type
#>    - tagslist tags

########################################
  site-nav-left:

    MENU:
    SPACE:
    CONTENTS:
      - box-begin 0 Contents
      - contents 0
      - box-end
    METADATA:
#>    - spacer
#>    - tagslist author
#>    - tagslist type
#>    - tagslist tags
#>    - readtime

########################################
  site-nav-right:

    MENU:
    SPACE:
    LIBRARY:
      - fold-begin group fold-library
      - fold-begin 0 0 fold-library Authors
      - library author
      - fold-end
      - fold-begin 0 0 fold-library Types
      - library type
      - fold-end
      - fold-begin 0 0 fold-library Tags
      - library tags
      - fold-end
      - fold-begin 0 0 fold-library History
      - library date
      - fold-end

########################################
  site-info-top:

    TEXT:
    INFO:
    ICON:
#>    - icon <composer_root>/../garybgenett/_branding/logo.png author http://www.garybgenett.net Gary B. Genett

########################################
  site-info-bottom:

    TEXT:
    INFO:
      - readtime
    ICON:

################################################################################
# end of file
################################################################################
