variables:
  site-nav-top:
    CONTENTS:
      - Contents:
          - contents 0
  site-nav-left:
    CONTENTS:
      - box-begin 0 Contents
      - contents 0
      - box-end
  site-library:
    folder:
      name: null
      auto_update: null
